services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - 4567:4567/tcp
      - 4567:4567/udp
      - 5678:5678/tcp
    volumes:
      - /mnt/data/satisfactory:/config
    environment:
      - MAXPLAYERS=$MAXPLAYERS
      - PGID=$PGID
      - PUID=$PUID
      - SERVERGAMEPORT=$SERVERGAMEPORT
      - SERVERMESSAGINGPORT=$SERVERMESSAGINGPORT
      - STEAMBETA=false
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G